sudo: false
language: ruby
rvm:
  - 2.7.7
before_install: gem install bundler
notifications:
  slack:
    secure: YyIkkmNX3lE0O6kf+ccXclTFO2WLT279rHlZNNkLy4JcZ2BhAmAvWBxB449JIwPEayx9/2Fd/I9g2djpj9kzNj+L1CZXuUXrNZ3j2vOT+8OMnPhxIRBJmFCm4+WDWlGBMcOG4WXu5MJtkiCHmfZYLWju79pCX/1KgasLT1t/OPQ9UfnoOOM96jfmFMzb9w5fE4O9njVekNgVWxouzvZDr9+PZad27Wl/5GWFGLixxT8MBVyMUsH68Tb03biM5heE1kL6+kIXGxwNCem1JgR8/YUjqW6t2/pvuWbMXFu1yAWHhFnFaKBHfcoA9eAMNLfxF37hUlSWdB8hESAPF9eoPbYEXnFA0O7EhJV/e/TIO6J7T+USCUbnndDBwh2tLPAjpwwFjm0I6PhlfTGWbUrR9ArvjQLMfv40rV0Z1jAbrWGFwPgc6n76OkS6d+4mkIzBJUX1LjRx0Cdgz+cq7USIcNbuqP+5PTkw+c075lL2CMwrNRamU1yPnCZQ4haXrPjBfr/UrLmg3/4Og8ohQC6A4kG8FUV0wBozXAaNVmcdYIvtDCVLIwg8FryrIuNstpmI7P2IajXCehDkOIueYZvv+DVpm8LkUsSeZuqyPK2hRa8oNRvSZh2I+7IARQNfPuDFDIyKchmHwhOC1OouUR0ZF7gxydTQ3eYGKqrXQR87P/8=
